"""add login, passwd, elective_course columns

Revision ID: 0b9cb4efc307
Revises: df58d518ad5f
Create Date: 2024-04-12 10:12:19.760990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9cb4efc307'
down_revision: Union[str, None] = 'df58d518ad5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('password', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('elective_courses', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'elective_courses')
    op.drop_column('users', 'password')
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
