"""add Elective Course table real

Revision ID: 295e28cbf09a
Revises: 8598a1d1244e
Create Date: 2024-05-02 21:51:35.987645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295e28cbf09a'
down_revision: Union[str, None] = '8598a1d1244e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'elective_course', ['subject'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_table('elective_transactions',
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_name'], ['elective_course.subject'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('course_name', 'user_id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'elective_course', type_='unique')
    op.drop_table('elective_transactions')
    # ### end Alembic commands ###
