"""delete unused field (name)

Revision ID: 4d6b42dd095b
Revises: 0b9cb4efc307
Create Date: 2024-04-21 20:30:09.561569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6b42dd095b'
down_revision: Union[str, None] = '0b9cb4efc307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elective_course', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elective_course', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
