"""add diffs column in elective course

Revision ID: 763fffdc19e8
Revises: 925356043ff7
Create Date: 2024-05-18 15:23:36.865926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763fffdc19e8'
down_revision: Union[str, None] = '925356043ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elective_course', sa.Column('diffs_teacher', sa.String(), nullable=True))
    op.add_column('elective_course', sa.Column('diffs_auditory', sa.String(), nullable=True))
    op.add_column('elective_course', sa.Column('is_cancelled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elective_course', 'is_cancelled')
    op.drop_column('elective_course', 'diffs_auditory')
    op.drop_column('elective_course', 'diffs_teacher')
    # ### end Alembic commands ###
