"""hotfix null values in users

Revision ID: 76cdbfbf802c
Revises: 1744a92300f3
Create Date: 2024-09-18 22:10:48.223539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cdbfbf802c'
down_revision: Union[str, None] = '1744a92300f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
