"""add is_diffs column in elective course

Revision ID: 925356043ff7
Revises: ad900aace3fc
Create Date: 2024-05-15 12:51:34.338811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925356043ff7'
down_revision: Union[str, None] = 'ad900aace3fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elective_course', sa.Column('is_diffs', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elective_course', 'is_diffs')
    # ### end Alembic commands ###
