"""add diffs_time_from and diffs_time_to

Revision ID: a6f866c91243
Revises: a83040361ec6
Create Date: 2024-08-20 16:41:12.884074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6f866c91243'
down_revision: Union[str, None] = 'a83040361ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elective_course', sa.Column('diffs_time_from', sa.Time(), nullable=True))
    op.add_column('elective_course', sa.Column('diffs_time_to', sa.Time(), nullable=True))
    op.alter_column('elective_course', 'time_from',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('elective_course', 'time_to',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('elective_course', 'auditory',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('elective_course', 'auditory',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('elective_course', 'time_to',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('elective_course', 'time_from',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.drop_column('elective_course', 'diffs_time_to')
    op.drop_column('elective_course', 'diffs_time_from')
    # ### end Alembic commands ###
