"""add ondelete param

Revision ID: a83040361ec6
Revises: 763fffdc19e8
Create Date: 2024-05-27 22:18:29.199544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83040361ec6'
down_revision: Union[str, None] = '763fffdc19e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('elective_transactions_user_id_fkey', 'elective_transactions', type_='foreignkey')
    op.drop_constraint('elective_transactions_course_name_fkey', 'elective_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'elective_transactions', 'elective_course', ['course_name'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'elective_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'elective_transactions', type_='foreignkey')
    op.drop_constraint(None, 'elective_transactions', type_='foreignkey')
    op.create_foreign_key('elective_transactions_course_name_fkey', 'elective_transactions', 'elective_course', ['course_name'], ['id'])
    op.create_foreign_key('elective_transactions_user_id_fkey', 'elective_transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
