"""add auditory column in elective course

Revision ID: ad900aace3fc
Revises: 09e1a3172bf2
Create Date: 2024-05-15 12:12:21.157647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad900aace3fc'
down_revision: Union[str, None] = '09e1a3172bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elective_course', sa.Column('auditory', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elective_course', 'auditory')
    # ### end Alembic commands ###
