"""empty message

Revision ID: bf1cc356884d
Revises: ba7d9a7420ff
Create Date: 2023-12-06 11:27:43.391400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bf1cc356884d'
down_revision: Union[str, None] = 'ba7d9a7420ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.Text(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
                    existing_type=sa.Text(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    # ### end Alembic commands ###
