"""add time_to column

Revision ID: de332dbe1bb4
Revises: 427f20c31c12
Create Date: 2024-05-10 15:44:21.048566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de332dbe1bb4'
down_revision: Union[str, None] = '427f20c31c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elective_course', sa.Column('time_from', sa.Time(), nullable=False))
    op.add_column('elective_course', sa.Column('time_to', sa.Time(), nullable=False))
    op.drop_column('elective_course', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elective_course', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('elective_course', 'time_to')
    op.drop_column('elective_course', 'time_from')
    # ### end Alembic commands ###
