"""add elective_course table

Revision ID: df58d518ad5f
Revises: f73d10ba0a83
Create Date: 2024-03-26 14:23:35.817982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df58d518ad5f'
down_revision: Union[str, None] = 'f73d10ba0a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elective_course',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('pulpit', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('timetable', sa.Text(), nullable=False),
    sa.Column('teacher_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.add_column('changes', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('changes', 'id')
    op.drop_table('elective_course')
    # ### end Alembic commands ###
