"""add changes table

Revision ID: f73d10ba0a83
Revises: ab3a72801dbd
Create Date: 2024-01-27 17:58:45.658554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73d10ba0a83'
down_revision: Union[str, None] = 'ab3a72801dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changes',
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('second', sa.Text(), nullable=False),
    sa.Column('weekday', sa.Text(), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('changes')
    # ### end Alembic commands ###
