# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drawing.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'drawing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdrawing.proto\x12\x04\x64raw\"L\n\x06Lesson\x12\x14\n\x0clessonNumber\x18\x01 \x01(\x05\x12\r\n\x05\x66irst\x18\x02 \x01(\t\x12\x0e\n\x06second\x18\x03 \x01(\t\x12\r\n\x05third\x18\x04 \x01(\t\"L\n\x0b\x44rawRequest\x12\x1d\n\x07lessons\x18\x01 \x03(\x0b\x32\x0c.draw.Lesson\x12\x1e\n\tdrawStyle\x18\x02 \x01(\x0e\x32\x0b.draw.Style\"#\n\x0c\x44rawResponse\x12\x13\n\x0bpathToImage\x18\x01 \x01(\t*c\n\x05Style\x12\x0b\n\x07\x43lassic\x10\x00\x12\x08\n\x04Rose\x10\x01\x12\x0f\n\x0bPrintStream\x10\x02\x12\r\n\tCyberpunk\x10\x03\x12\t\n\x05Space\x10\x04\x12\x07\n\x03\x43\x42O\x10\x05\x12\x0f\n\x0bRyanGosling\x10\x06\x32\x37\n\x06\x44rawer\x12-\n\x04\x44raw\x12\x11.draw.DrawRequest\x1a\x12.draw.DrawResponseB\x11\xaa\x02\x0e\x44rawingServiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drawing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016DrawingService'
  _globals['_STYLE']._serialized_start=216
  _globals['_STYLE']._serialized_end=315
  _globals['_LESSON']._serialized_start=23
  _globals['_LESSON']._serialized_end=99
  _globals['_DRAWREQUEST']._serialized_start=101
  _globals['_DRAWREQUEST']._serialized_end=177
  _globals['_DRAWRESPONSE']._serialized_start=179
  _globals['_DRAWRESPONSE']._serialized_end=214
  _globals['_DRAWER']._serialized_start=317
  _globals['_DRAWER']._serialized_end=372
# @@protoc_insertion_point(module_scope)
